application: quicktranlsate
version: 1
runtime: python27
api_version: 1
threadsafe: yes

default_expiration: "1d"

handlers:
- url: /styles
  static_dir: dist/styles
  secure: always
- url: /fonts
  static_dir: dist/fonts
  secure: always
- url: /scripts
  static_dir: dist/scripts
  secure: always
- url: /
  static_files: dist/index.html
  upload: dist/index.html
  secure: always
- url: /
  static_dir: dist
  secure: always

libraries:
- name: webapp2
  version: "2.5.2"

skip_files:
-  ^node_modules/?
-  ^app/? 
-  ^test/? 
