application: quicktranlsate
version: 1
runtime: python27
api_version: 1
threadsafe: yes

default_expiration: "1d"

handlers:
- url: /styles
  static_dir: dist/styles
- url: /fonts
  static_dir: dist/fonts
- url: /scripts
  static_dir: dist/scripts
- url: /
  static_dir: dist

libraries:
- name: webapp2
  version: "2.5.2"

skip_files:
-  ^node_modules/?
-  ^app/? 
-  ^test/? 
